### ISSUE TITLE
C file

### ISSUE THREAD

**Issue by retroarch-girl** [boombuler/aseprite-gbexport#1]
Hi

Is it possible to add also C file export?

**Comment by boombuler** [comment]
Should be an easy tweak if you tell me what you need. I guess some kine of #define or an array initialisation of the tile data?

**Comment by retroarch-girl** [comment]
I'm just starting GBDK, so I just need a file that can be used for GBDK (not sure what that is right now...)

So I currently use these tools, you can see how to export it:

https://github.com/gbdk-2020/GBTD_GBMB/releases/tag/2.4.5

If you could use that same format, it would be great. Because aseprite is better then those tools.

in game boy map builder: 

![afbeelding](https://github.com/boombuler/aseprite-gbexport/assets/132721852/51dc8d9a-7bb9-4844-828e-dc26bf0dede9)

in game boy tile designer:

![afbeelding](https://github.com/boombuler/aseprite-gbexport/assets/132721852/c163e9fb-7490-40fd-a9da-dc0022c13985)

**Comment by retroarch-girl** [comment]
More info

https://laroldsjubilantjunkyard.com/tutorials/how-to-make-a-gameboy-game/sprites-and-backgrounds/

**Comment by retroarch-girl** [comment]
- When I use the game boy color palette in aseprite, will the colors be exported the same as on the screen.

- What happens if you use more then 4 colors and/or not use the game boy color palette?

**Comment by boombuler** [comment]
About the color palette:
The gameboy has configurable color palettes (See https://gbdev.io/pandocs/Palettes.html) so this explort exports the indices of your current asprite palette, which is also useful if you want to tinker with the gb color features.
If you use more then 4 colors in your image, the plaette will restart (so if you use the 5th color, the 1st will be used instead)

Without any code change you could use it with some minor editing of the export:

If you have a look at my "Flappy Bird Clone" there is an [asprite floor file](https://github.com/boombuler/gbflappybird/blob/master/images/Floor.aseprite) which exports to [this](https://github.com/boombuler/gbflappybird/blob/master/images/floor.inc) assembly file
when you take the content of the assembly file:

```assembly
DB $90, $00, $a6, $10, $ff, $00, $66, $99, $00, $ff, $23, $ff, $ef, $ff, $ff, $ff
```

then you just need to strip the "DB" at the start of the line (each line if you have multiple tiles) and replace the `$` with an `0x`
and create the following C snippit from it:

```C
unsigned char Floor[] = 
{
0x90, 0x00, 0xa6, 0x10, 0xff, 0x00, 0x66, 0x99, 0x00, 0xff, 0x23, 0xff, 0xef, 0xff, 0xff, 0xff
}
```

Let me know if this works for you, if so then it should only be a hand full of changes.

**Comment by retroarch-girl** [comment]
I can't answer this question
I"m abeginner in GBDK, aseprite and never used it.
I'm looking for a plugin so I can export it to C file.

sorry

**Comment by boombuler** [comment]
https://github.com/redboyrave/Aseprite-GB-Exporter probably serves your needs.

**Comment by retroarch-girl** [comment]
It gives error
stupid shit

YOU ALL ARE FUCKING LOSERS
NOTHING WORKS ON GITHUB!!!!!!!!!!!!!!

**Comment by boombuler** [comment]
Maybe try to understand the workings of the Gameboy graphic system? With that knowledge only 3-4 lines of my code needs to be changed to export a .c file for gbdk. Anyway, good luck getting help from people spending their free time with an attitude like that...

**Comment by retroarch-girl** [comment]
FUCK YOU UGLY MOTHERFOKER

**Comment by retroarch-girl** [comment]
FUCKFACE

**Comment by retroarch-girl** [comment]
YOU LOOK LIKE PIG

**Comment by retroarch-girl** [comment]
OINK OINK

**Comment by retroarch-girl** [comment]
WEEEEEEEEEEEEEEEEET

**Comment by retroarch-girl** [comment]
OINK OINK OINK
